import Head from "next/head";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/react";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";

export default function Home() {
  const { data: session, status } = useSession();
  console.log(session)

  if (status === "loading") return null;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.container}>
        <h1>Goggle Authentication With NextAuth</h1>
        {!session && (
          <>
            <button className={styles.primaryButton} onClick={() => signIn()}>Sign In</button>
          </>
        )}
        {session && (
          <>
            <h4>You are logged as: {session.user.name}</h4>
            <div className={styles.boxCenter}>
              <h4>Email: {session.user.email}</h4>
              <br />
              {session.user.image && (
                <span>
                  <img src={session.user.image} alt={session.user.name} />
                </span>
              )}
            </div>
            <br />
            <br />
            <button className={styles.primaryButton} onClick={() => signOut()}>
              Sign Out
            </button>
          </>
        )}
      </div>
    </div>
  );
}
